name: Publish Windows binary

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up MSYS2 with UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-qt6-base
            zip

      - name: Build
        shell: msys2 {0}
        run: |
          cmake -B build
          cmake --build build

      - name: Copy executable and dependencies
        shell: msys2 {0}
        run: |
          mkdir "casekey-${{ github.ref_name }}"
          mkdir "casekey-${{ github.ref_name }}/docs"
          # copy binary
          cp build/casekey.exe "casekey-${{ github.ref_name }}/"
          # copy docs
          cp README.md CHANGELOG.md FAQ.md LICENSE "casekey-${{ github.ref_name }}/docs/"
          # bundle needed libraries
          cd "casekey-${{ github.ref_name }}/"
          ldd casekey.exe | grep /ucrt64 | awk '{print $3}' | xargs -i cp {} .
          # Run Qt's windows deployment tool
          windeployqt6.exe casekey.exe \
            --release \
            --no-libraries \
            --no-translations \
            --no-quick-import \
            --no-system-d3d-compiler \
            --no-system-dxc-compiler \
            --no-compiler-runtime \
            --no-opengl-sw \
            --no-ffmpeg

      - name: Zip release artifacts
        shell: msys2 {0}
        run: |
          zip -r "casekey-${{ github.ref_name }}-windows-x64.zip" "casekey-${{ github.ref_name }}"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: "casekey-${{ github.ref_name }}-windows-x64.zip"
